name: Build & Deploy Backend

on:
  push:
    branches:
      - main # prod
      - test
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
      - "compose.yaml"

jobs:
  build-backend:
    runs-on: self-hosted

    # set which env to pull secrets/vars from
    environment: ${{ github.ref_name == 'main' && 'prod' || 'test' }}

    env:
      ENV: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
      COMPOSE_PROJECT_NAME: "pwsite-${{ github.ref_name == 'main' && 'prod' || 'test' }}"
      BACKEND_PORT: ${{ vars.BACKEND_PORT }}
      PHOTO_LIBRARY: ${{ vars.PHOTO_LIBRARY }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
      IMAGE_NAME: "pwsite-${{ github.ref_name == 'main' && 'prod' || 'test' }}-backend"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Save image
        run: mkdir -p /tmp/pwsite-images && docker save -o /tmp/pwsite-images/${{ env.IMAGE_NAME }}.tar ${{ env.IMAGE_NAME }}:latest

  deploy-backend-container:
    runs-on: self-hosted
    needs: build-backend

    # set which env to pull secrets/vars from
    environment: ${{ github.ref_name == 'main' && 'prod' || 'test' }}

    env:
      ENV: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
      COMPOSE_PROJECT_NAME: "pwsite-${{ github.ref_name == 'main' && 'prod' || 'test' }}"
      BACKEND_PORT: ${{ vars.BACKEND_PORT }}
      PHOTO_LIBRARY: ${{ vars.PHOTO_LIBRARY }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
      IMAGE_NAME: "pwsite-${{ github.ref_name == 'main' && 'prod' || 'test' }}-backend"

    steps:
      - name: Load image
        run: |
          docker load --input /tmp/pwsite-images/${{ env.IMAGE_NAME }}.tar
          docker image ls -a
          rm /tmp/pwsite-images/${{ env.IMAGE_NAME }}.tar

      - name: Restart Backend Service
        run: |
          docker compose up -d --no-deps backend
