name: Build & Deploy Frontend

on:
  push:
    branches:
      - main # prod
      - test
    paths-ignore:
      - 'backend/**'
      - 'admin/**'
      - 'README.md'
      - '**/README.md'
      - '*.example'
      - '.gitignore'
      - '.github/workflows/backend.yml'
      - '.github/workflows/admin.yml'
      - '.github/workflows/database.yml'

jobs:
  build-frontend:
    runs-on: self-hosted

    env:
      ENV: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
      COMPOSE_PROJECT_NAME: "pwsite-${{ github.ref_name == 'main' && 'prod' || 'test' }}"
      APP_PORT: ${{ vars.APP_PORT }}
      PHOTO_LIBRARY: ${{ vars.PHOTO_LIBRARY }}
      API_URL: 'http://backend:8080'
      IMAGE_TAG: "pwsite-${{ github.ref_name == 'main' && 'prod' || 'test' }}-app:latest"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: ${{ env.IMAGE_TAG }}, app:latest
          labels:
            - "environment=${{ github.ref_name }}"

  deploy-frontend:
    runs-on: self-hosted
    needs: build-frontend

    env:
      ENV: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
      COMPOSE_PROJECT_NAME: "pwsite-${{ github.ref_name == 'main' && 'prod' || 'test' }}"
      APP_PORT: ${{ vars.APP_PORT }}
      PHOTO_LIBRARY: ${{ vars.PHOTO_LIBRARY }}
      API_URL: 'http://backend:8080'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Save Frontend Image
        run: |
          docker save -o frontend-app.tar ${{ env.IMAGE_TAG }}, app:latest

      - name: Upload frontend image artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-image
          path: frontend-app.tar
          retention-days: 1

  deploy-frontend-container:
    runs-on: self-hosted
    needs: deploy-frontend

    env:
      ENV: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
      COMPOSE_PROJECT_NAME: "pwsite-${{ github.ref_name == 'main' && 'prod' || 'test' }}"
      APP_PORT: ${{ vars.APP_PORT }}
      PHOTO_LIBRARY: ${{ vars.PHOTO_LIBRARY }}
      API_URL: 'http://backend:8080'

    steps:
      - uses: actions/checkout@v4

      - name: Download frontend image artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-image
          path: .

      - name: Load Frontend Image
        run: |
          docker load -i frontend-app.tar
          rm frontend-app.tar

      - name: Restart Frontend Service
        run: |
          docker compose up -d --no-deps --build app

      - name: (prod) Connect to Proxy Network
        run: docker network connect nathan_default pwsite-${{ env.ENV }}-app
