name: Build & Deploy Frontend

on:
  push:
    branches:
      - main # prod
      - test
    paths-ignore:
      - 'backend/**'
      - 'admin/**'
      - 'README.md'
      - '**/README.md'
      - '*.example'
      - '.gitignore'
      - '.github/workflows/backend.yml'
      - '.github/workflows/admin.yml'
      - '.github/workflows/database.yml'

jobs:
  build-frontend:
    runs-on: self-hosted

    # set which env to pull secrets/vars from
    environment: ${{ github.ref_name == 'main' && 'prod' || 'test' }}

    env:
      ENV: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
      COMPOSE_PROJECT_NAME: "pwsite-${{ github.ref_name == 'main' && 'prod' || 'test' }}"
      APP_PORT: ${{ vars.APP_PORT }}
      PHOTO_LIBRARY: ${{ vars.PHOTO_LIBRARY }}
      API_URL: 'http://backend:8080'
      IMAGE_NAME: "pwsite-${{ github.ref_name == 'main' && 'prod' || 'test' }}-app"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Save image
        run: docker save -o ${{ runner.temp }}/${{ env.IMAGE_NAME }}.tar ${{ env.IMAGE_NAME }}:latest

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}-image
          path: ${{ runner.temp }}/${{ env.IMAGE_NAME }}.tar
          retention-days: 1

  deploy-frontend-container:
    runs-on: self-hosted
    needs: build-frontend

    # set which env to pull secrets/vars from
    environment: ${{ github.ref_name == 'main' && 'prod' || 'test' }}

    env:
      ENV: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
      COMPOSE_PROJECT_NAME: "pwsite-${{ github.ref_name == 'main' && 'prod' || 'test' }}"
      APP_PORT: ${{ vars.APP_PORT }}
      PHOTO_LIBRARY: ${{ vars.PHOTO_LIBRARY }}
      API_URL: 'http://backend:8080'
      IMAGE_NAME: "pwsite-${{ github.ref_name == 'main' && 'prod' || 'test' }}-app"

    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}-image
          path: ${{ runner.temp }}

      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/${{ env.IMAGE_NAME }}.tar
          docker image ls -a
          rm ${{ runner.temp }}/${{ env.IMAGE_NAME }}.tar

      - name: Restart Frontend Service
        run: |
          docker compose up -d --no-deps --build app

      - name: (prod) Connect to Proxy Network
        run: docker network connect nathan_default pwsite-${{ env.ENV }}-app
